import { PALETTE_COLORS } from '@/bp-theme';
import { SxProps } from '@mui/material';

const ACCENT = PALETTE_COLORS.neon_orange;
const MUTED = '#6b7280';
const PLACEHOLDER = '#9aa0a6';

const RENDER_FONT = "'Kumbh Sans', Arial, Verdana";
const RENDER_INK = '#2b2b2a';
const RENDER_RULE = '1px solid #e0e0e0';

export const CustomPageEditorStyle: SxProps = {
  display: 'flex',
  flexDirection: 'column',
  width: '100%',
  height: '86vh',
  bgcolor: PALETTE_COLORS.white,

  '& .editor-bar': {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    flexShrink: 0,
    px: 2,
    py: 1.5,
    borderBottom: '1px solid rgba(0, 0, 0, 0.08)',
  },
  '& .editor-back': {
    flexShrink: 0,
    color: MUTED,
  },
  '& .editor-heading': {
    flex: 1,
    minWidth: 0,
    fontSize: 15,
    fontWeight: 700,
    color: PALETTE_COLORS.forest,
  },
  '& .editor-bar .bar-btn': {
    minWidth: 104,
    textTransform: 'none',
    fontWeight: 600,
  },

  '& .editor-canvas': {
    flex: 1,
    minHeight: 0,
    overflow: 'auto',
    bgcolor: '#f1f3f4',
    p: 2,
  },

  '& .page-sheet': {
    width: 794,
    minHeight: 1123,
    maxWidth: '100%',
    mx: 'auto',
    px: '30px',
    py: '20px',
    bgcolor: PALETTE_COLORS.white,
    boxShadow: '0 1px 3px rgba(60, 64, 67, 0.3), 0 4px 8px 3px rgba(60, 64, 67, 0.15)',
    fontFamily: RENDER_FONT,
    fontSize: 12,
    lineHeight: 1.5,
    color: RENDER_INK,
  },

  '& .page-sheet .MuiInputBase-root': {
    fontFamily: 'inherit',
    letterSpacing: 'inherit',
  },
  '& .page-sheet .MuiInputBase-input': {
    font: 'inherit',
    color: 'inherit',
    textAlign: 'inherit',
    letterSpacing: 'inherit',
    p: 0,
  },
  '& .page-sheet .MuiInputBase-input::placeholder': {
    color: PLACEHOLDER,
    opacity: 1,
    fontStyle: 'normal',
  },

  '& .page-title': {
    display: 'block',
    width: '100%',
    fontSize: 19.2,
    fontWeight: 700,
    color: ACCENT,
    textAlign: 'center',
    pb: '8px',
    mb: '20px',
  },
  '& .page-hint': {
    fontFamily: RENDER_FONT,
    fontSize: 12,
    color: PLACEHOLDER,
    textAlign: 'center',
    py: 4,
  },

  '& .blocks': {
    display: 'flex',
    flexDirection: 'column',
  },
  '& .block': {
    position: 'relative',
    width: '100%',
    mb: '25px',
    outline: '1px solid transparent',
    outlineOffset: 4,
    transition: 'outline-color 0.15s ease',
    '&:hover': { outlineColor: 'rgba(0, 0, 0, 0.12)' },
  },
  '& .block-toolbar': {
    position: 'absolute',
    top: -40,
    right: -6,
    display: 'flex',
    gap: '4px',
    opacity: 0,
    transition: 'opacity 0.15s ease',
    zIndex: 1,
  },
  '& .block:hover .block-toolbar, & .block:focus-within .block-toolbar': { opacity: 1 },
  '& .block-menu': {
    color: '#9ca3af',
    bgcolor: PALETTE_COLORS.white,
    border: '1px solid rgba(0, 0, 0, 0.12)',
    '&:hover': { color: PALETTE_COLORS.black, bgcolor: PALETTE_COLORS.white },
  },
  '& .block-move-controls': {
    position: 'absolute',
    top: '50%',
    left: -34,
    transform: 'translateY(-50%)',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    opacity: 0,
    transition: 'opacity 0.15s ease',
    zIndex: 1,
  },
  '& .block:hover .block-move-controls, & .block:focus-within .block-move-controls': { opacity: 1 },
  '& .block-move': {
    color: '#9ca3af',
    bgcolor: PALETTE_COLORS.white,
    border: '1px solid rgba(0, 0, 0, 0.12)',
    '&:hover': { color: PALETTE_COLORS.black, bgcolor: PALETTE_COLORS.white },
    '&.Mui-disabled': { color: 'rgba(0, 0, 0, 0.26)', bgcolor: 'rgba(0, 0, 0, 0.04)' },
  },

  '& .block-text': {
    display: 'block',
    width: '100%',
    lineHeight: 1.7,
    textAlign: 'justify',
    color: RENDER_INK,
  },
  '& .block-text.prio-important': {
    fontSize: 15,
    fontWeight: 700,
    color: '#080707',
  },
  '& .block-text.prio-medium': {
    fontSize: 12.6,
    fontWeight: 600,
    color: '#6b6b6b',
  },
  '& .block-text.prio-small': {
    fontSize: 10.8,
    color: '#6b6b6b',
  },

  '& .block-image': {
    textAlign: 'center',
    my: '15px',
  },
  '& .image-frame': {
    display: 'inline-block',
    width: '80%',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  '& .block-image.prio-important .image-frame': { width: '100%' },
  '& .block-image.prio-small .image-frame': { width: '60%' },
  '& .image-preview': {
    display: 'block',
    width: '100%',
    height: 'auto',
    borderRadius: '4px',
    border: RENDER_RULE,
  },
  '& .image-caption': {
    display: 'block',
    width: '100%',
    fontSize: 10.2,
    fontStyle: 'italic',
    color: '#888780',
    textAlign: 'center',
    mt: '6px',
  },

  '& .image-drop': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    minHeight: 140,
    px: 2,
    borderRadius: '4px',
    border: '2px dashed rgba(0, 0, 0, 0.16)',
    bgcolor: 'rgba(0, 0, 0, 0.015)',
    transition: 'border-color 0.15s ease, background-color 0.15s ease',
    '&:hover': { borderColor: ACCENT, bgcolor: 'rgba(255, 82, 27, 0.04)' },
  },
  '& .block-image.prio-important .image-drop': { width: '100%', minHeight: 180 },
  '& .block-image.prio-small .image-drop': { width: '60%', minHeight: 110 },
  '& .image-drop-target': {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    width: '100%',
    minHeight: 'inherit',
    color: PLACEHOLDER,
    '& svg': { fontSize: 24 },
  },
  '& .image-choice': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.5,
    width: '100%',
    minHeight: 38,
    px: 2,
    borderRadius: '4px',
    color: PLACEHOLDER,
    '&:hover': { bgcolor: 'rgba(0, 0, 0, 0.03)' },
  },
  '& .image-drop-label': {
    fontFamily: RENDER_FONT,
    fontSize: 12,
    fontWeight: 500,
  },
  '& .image-url': {
    width: '100%',
    fontSize: 12,
    textAlign: 'center',
  },

  '& .render-table': {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: 0,
    my: '18px',
  },
  '& .render-table th': {
    bgcolor: '#f7f7f5',
    fontWeight: 700,
    textAlign: 'center',
    p: '6px 8px',
  },
  '& .render-table td': {
    p: '10px 8px',
    lineHeight: 1.5,
    borderBottom: RENDER_RULE,
    verticalAlign: 'top',
  },
  '& .render-table td:first-of-type': {
    fontWeight: 700,
    width: '30%',
    bgcolor: '#f8f8f8',
  },
  '& .render-table tbody tr:nth-of-type(even) td': { bgcolor: '#fafafa' },
  '& .render-table tbody tr:last-of-type td': { borderBottom: 'none' },

  '& .table-controls': {
    display: 'flex',
    gap: 1.5,
    mt: -1,
    opacity: 0,
    transition: 'opacity 0.15s ease',
  },
  '& .block:hover .table-controls, & .block:focus-within .table-controls': { opacity: 1 },
  '& .table-control': {
    fontFamily: RENDER_FONT,
    fontSize: 11,
    fontWeight: 600,
    color: MUTED,
    px: 0.5,
    borderRadius: '4px',
    '&:hover': { color: ACCENT },
    '&.Mui-disabled': { opacity: 0.4 },
  },

  '& .block-columns': {
    display: 'grid',
    justifyContent: 'space-between',
    width: '100%',
  },
  '& .column': {
    position: 'relative',
    minWidth: 0,
  },
  '& .column-toolbar': {
    position: 'absolute',
    top: -6,
    right: -6,
    display: 'flex',
    gap: '4px',
    opacity: 0,
    transition: 'opacity 0.15s ease',
    zIndex: 1,
  },
  '& .column:hover .column-toolbar, & .column:focus-within .column-toolbar': { opacity: 1 },
  '& .column-count-controls': {
    display: 'flex',
    justifyContent: 'center',
    gap: 1.5,
    mt: 1,
    opacity: 0,
    transition: 'opacity 0.15s ease',
  },
  '& .block:hover .column-count-controls, & .block:focus-within .column-count-controls': { opacity: 1 },

  '& .add-block': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.75,
    width: '100%',
    mt: 1,
    py: 1.25,
    borderRadius: '4px',
    border: '1px dashed rgba(0, 0, 0, 0.16)',
    fontFamily: RENDER_FONT,
    fontSize: 12,
    fontWeight: 600,
    color: MUTED,
    transition: 'border-color 0.15s ease, color 0.15s ease, background-color 0.15s ease',
    '&:hover': { borderColor: ACCENT, color: ACCENT, bgcolor: 'rgba(255, 82, 27, 0.04)' },
  },
};
