import { PALETTE_COLORS } from '@/common/config/theme';
import { SxProps } from '@mui/material';

export const AccountStyle: SxProps = {
  width: '100%',
  py: 4,
  bgcolor: '#ffffffff',
  '& #container': {
    maxWidth: '1400px',
    mx: 'auto',
    px: 2,
  },
  '& .card': {
    borderRadius: 3,
    boxShadow: '0 2px 10px #4F6350',
    bgcolor: '#fff',
    p: 2,
    minHeight: '250px',
  },
  '& .card-user': {
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  '& .user-header': {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    mb: 1,
  },
  '& .avatar': {
    width: 170,
    height: 170,
  },
  '& .card-trial': {
    textAlign: 'center',
    bgcolor: '#ffffffff',
  },
  '& .company-card': {
    mt: 3,
  },
  '& .section-title': {
    backgroundColor: PALETTE_COLORS.pine,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    borderRadius: 25,
    py: 1,
    mb: 3,
    mx: 'auto',
    fontSize: '1.3rem',
    width: '400px',
  },
  '& .section-title-company': {
    backgroundColor: PALETTE_COLORS.pine,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    borderRadius: 25,
    py: 1,
    mb: 6,
    mx: 'auto',
    fontSize: '1.3rem',
    width: '500px',
  },
  '& .section-title-subscription': {
    backgroundColor: PALETTE_COLORS.pine,
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    borderRadius: 25,
    py: 1,
    mb: 3,
    mx: 'auto',
    fontSize: '1.3rem',
    width: '500px',
  },
  '& .MuiTextField-root': {
    bgcolor: '#fafafa',
  },
  '& .MuiOutlinedInput-root': {
    borderRadius: '12px',
  },
  '& .container-typo-user': {
    ml: 7,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  '& .typo-user': {
    my: 1.2,
    fontWeight: 'bold',
  },
  '& .subscription-card': {
    mt: 3,
  },
  '& .price-subscription': {
    border: '1px solid #000000',
    borderRadius: 25,
    color: PALETTE_COLORS.neon_orange,
    pl: 4,
    py: 1,
    width: '17%',
    textAlign: 'left',
    ml: 3,
    mb: 3,
    fontSize: '1.1rem',
    fontWeight: 'bold',
  },
  '& .list-subscription': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '0,8rem',
    my: 2,
    mr: 5,
  },
  '& .arrow-list': {
    color: PALETTE_COLORS.neon_orange,
    fontSize: '2.8rem',
    ml: 5,
  },
};
