import { PALETTE_COLORS } from '@/common/config/theme';
import { alpha, SxProps } from '@mui/material';

const ORANGE = PALETTE_COLORS.neon_orange;
const ORANGE_DARK = PALETTE_COLORS.neon_orange_dark;
const ORANGE_SOFT = PALETTE_COLORS.peach;
const TINT = PALETTE_COLORS.cream;
const WHITE = PALETTE_COLORS.white;
const TEXT = PALETTE_COLORS.black;
const MUTED = PALETTE_COLORS.stone;
const BORDER = PALETTE_COLORS.linen;
const DOTTED = PALETTE_COLORS.sand;

export const BillingModalStyle: SxProps = {
  '& .MuiDialog-paper': {
    borderRadius: '16px',
    bgcolor: WHITE,
  },

  '& .billing-title': {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '1.15rem',
    fontWeight: 700,
    color: PALETTE_COLORS.forest,
    pb: 1,
  },
  '& .billing-title-icon': {
    color: ORANGE,
    fontSize: '1.6rem',
  },

  '& .billing-content': {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },

  '& .billing-section': {
    border: `1px solid ${BORDER}`,
    borderRadius: '14px',
    padding: '16px',
    bgcolor: WHITE,
  },
  '& .billing-section-header': {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    marginBottom: '12px',
  },
  '& .billing-section-icon': {
    flexShrink: 0,
    width: '30px',
    height: '30px',
    borderRadius: '9px',
    bgcolor: ORANGE_SOFT,
    color: ORANGE_DARK,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  '& .billing-section-icon svg': { fontSize: '17px' },
  '& .billing-section-title': {
    fontSize: '14px',
    fontWeight: 700,
    color: TEXT,
    lineHeight: 1.3,
  },
  '& .billing-section-subtitle': {
    fontSize: '11px',
    color: MUTED,
    lineHeight: 1.35,
  },

  '& .billing-row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    flexWrap: 'wrap',
  },
  '& .billing-row-main': { minWidth: 0 },
  '& .billing-label': {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: MUTED,
  },
  '& .billing-value': {
    fontSize: '15px',
    fontWeight: 700,
    color: TEXT,
  },
  '& .billing-hint': {
    fontSize: '11px',
    color: MUTED,
    marginTop: '2px',
  },

  '& .billing-action': {
    textTransform: 'none',
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: 700,
    padding: '6px 16px',
    boxShadow: 'none',
    bgcolor: ORANGE,
    color: WHITE,
    whiteSpace: 'nowrap',
    '&:hover': { bgcolor: ORANGE_DARK, boxShadow: 'none' },
    '&.Mui-disabled': { bgcolor: TINT, color: MUTED },
  },
  '& .billing-action--outline': {
    bgcolor: 'transparent',
    color: ORANGE,
    border: `2px solid ${ORANGE}`,
    '&:hover': { bgcolor: ORANGE, color: WHITE },
    '&.Mui-disabled': { bgcolor: 'transparent', borderColor: BORDER },
  },
  '& .billing-action--danger': {
    bgcolor: 'transparent',
    color: 'error.main',
    border: '2px solid',
    borderColor: 'error.main',
    '&:hover': { bgcolor: 'error.main', color: WHITE },
    '&.Mui-disabled': { bgcolor: 'transparent', borderColor: BORDER },
  },

  '& .billing-state': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '12px',
    color: MUTED,
    padding: '8px 0',
  },

  '& .billing-plan': {
    marginBottom: '10px',
  },
  '& .billing-plan-name': {
    fontSize: '16px',
    fontWeight: 800,
    color: TEXT,
  },
  '& .billing-plan-description': {
    fontSize: '11px',
    color: MUTED,
  },
  '& .billing-plan-meta': {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px 32px',
    padding: '10px 0 0',
    borderTop: `1px dashed ${DOTTED}`,
  },
  '& .billing-plan-meta > *': {
    minWidth: '120px',
  },
  '& .billing-plan-price': {
    fontSize: '20px',
    fontWeight: 800,
    color: ORANGE,
    lineHeight: 1.1,
  },

  '& .billing-card': {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  '& .billing-card-brand': {
    width: '42px',
    height: '28px',
    borderRadius: '6px',
    border: `1px solid ${BORDER}`,
    bgcolor: TINT,
    color: PALETTE_COLORS.forest,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  '& .billing-card-brand svg': { fontSize: '18px' },
  '& .billing-card-number': {
    fontSize: '14px',
    fontWeight: 700,
    color: TEXT,
    letterSpacing: '0.08em',
  },

  '& .billing-credits-overview': {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    flexWrap: 'wrap',
  },
  '& .billing-donut': {
    position: 'relative',
    width: '168px',
    height: '168px',
    flexShrink: 0,
  },
  '& .billing-donut-center': {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    textAlign: 'center',
  },
  '& .billing-donut-value': {
    fontSize: '26px',
    fontWeight: 800,
    color: TEXT,
    lineHeight: 1.05,
  },
  '& .billing-donut-label': {
    fontSize: '10px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: MUTED,
    maxWidth: '104px',
  },
  '& .billing-donut-empty': {
    width: '168px',
    height: '168px',
    borderRadius: '50%',
    border: `12px solid ${TINT}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },

  '& .billing-donut-slice': {
    outline: 'none',
    transition: 'opacity 0.2s',
  },
  '& .billing-donut-slice--granted': { fill: ORANGE },
  '& .billing-donut-slice--purchased': { fill: PALETTE_COLORS.pine },
  '& .billing-donut:hover .billing-donut-slice': { opacity: 0.55 },
  '& .billing-donut .billing-donut-slice:hover': { opacity: 1 },

  '& .billing-credits-details': {
    flex: 1,
    minWidth: '220px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  '& .billing-credit-line': {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: TEXT,
  },
  '& .billing-credit-dot': {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  '& .billing-credit-dot--granted': { bgcolor: ORANGE },
  '& .billing-credit-dot--purchased': { bgcolor: PALETTE_COLORS.pine },
  '& .billing-credit-line-label': {
    flex: '0 0 auto',
    minWidth: '100px',
    fontSize: '12px',
    color: TEXT,
  },
  '& .billing-credit-line-value': {
    flex: '0 0 auto',
    minWidth: '56px',
    fontSize: '12px',
    fontWeight: 700,
    color: TEXT,
    textAlign: 'right',
  },
  '& .billing-credit-note': {
    fontSize: '11px',
    color: MUTED,
    lineHeight: 1.4,
    paddingTop: '6px',
    borderTop: `1px dashed ${DOTTED}`,
  },
  '& .billing-credit-note strong': { color: TEXT },

  '& .billing-packs-toggle': {
    marginTop: '14px',
    paddingTop: '12px',
    borderTop: `1px dashed ${DOTTED}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap',
  },
  '& .billing-packs': {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: '8px',
    marginTop: '12px',
  },
  '& .billing-pack': {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
    border: `1px solid ${BORDER}`,
    borderRadius: '12px',
    padding: '14px 10px 10px',
    bgcolor: WHITE,
    transition: 'transform 0.2s, box-shadow 0.2s',
    '&:hover': { transform: 'translateY(-3px)', boxShadow: '0 10px 26px rgba(43, 25, 8, 0.09)' },
  },
  '& .billing-pack--featured': {
    border: `2px solid ${ORANGE}`,
    bgcolor: TINT,
  },
  '& .billing-pack-badge': {
    position: 'absolute',
    top: '-9px',
    left: '50%',
    transform: 'translateX(-50%)',
    bgcolor: ORANGE,
    color: WHITE,
    fontSize: '9px',
    fontWeight: 700,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    padding: '3px 10px',
    borderRadius: '999px',
    whiteSpace: 'nowrap',
  },
  '& .billing-pack-credits': {
    fontSize: '17px',
    fontWeight: 800,
    color: TEXT,
    lineHeight: 1.15,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  '& .billing-pack-description': {
    fontSize: '10.5px',
    color: MUTED,
    lineHeight: 1.3,
    minHeight: '27px',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  '& .billing-pack-price': {
    fontSize: '17px',
    fontWeight: 800,
    color: ORANGE,
    lineHeight: 1.2,
    marginTop: '4px',
  },
  '& .billing-pack-price-hint': {
    fontSize: '10px',
    color: MUTED,
    lineHeight: 1.35,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  '& .billing-pack-custom': {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    marginTop: '2px',
  },
  '& .billing-pack-custom-input': {
    flex: 1,
    minWidth: 0,
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      fontSize: '13px',
      fontWeight: 700,
      bgcolor: WHITE,
    },
    '& .MuiOutlinedInput-input': { padding: '6px 8px' },
  },
  '& .billing-pack-custom-unit': {
    fontSize: '10px',
    color: MUTED,
  },
  '& .billing-pack-price-hint:last-of-type': { marginBottom: '10px' },
  '& .billing-pack-cta': {
    marginTop: 'auto',
    width: '100%',
    textTransform: 'none',
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: 700,
    padding: '6px 12px',
    boxShadow: 'none',
    bgcolor: ORANGE,
    color: WHITE,
    '&:hover': { bgcolor: ORANGE_DARK, boxShadow: 'none' },
    '&.Mui-disabled': { bgcolor: alpha(ORANGE, 0.35), color: WHITE },
  },

  '& .billing-invoice-period': {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '10px 14px',
    marginBottom: '12px',
    borderRadius: '10px',
    bgcolor: TINT,
  },
  '& .billing-invoice-period-label': {
    fontSize: '12px',
    fontWeight: 600,
    color: PALETTE_COLORS.forest,
  },
  '& .billing-invoice-year-select': {
    minWidth: '110px',
    bgcolor: WHITE,
    borderRadius: '8px',
    fontWeight: 600,
    '& .MuiOutlinedInput-notchedOutline': { borderColor: 'transparent' },
    '&:hover .MuiOutlinedInput-notchedOutline, &.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: ORANGE,
      borderWidth: '1px',
    },
  },
  '& .billing-invoice-months': {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' },
    gap: '8px',
  },
  '& .billing-invoice-month': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '8px 12px',
    borderRadius: '10px',
    border: `1px solid ${BORDER}`,
    transition: 'border-color .2s ease, box-shadow .2s ease',
    '&.is-available:hover': { borderColor: ORANGE, boxShadow: '0 6px 16px rgba(43, 25, 8, 0.08)' },
    '&.is-unavailable': { bgcolor: TINT, borderColor: 'transparent' },
  },
  '& .billing-invoice-month-name': {
    fontSize: '12px',
    fontWeight: 600,
    color: PALETTE_COLORS.forest,
  },
  '& .is-unavailable .billing-invoice-month-name': { color: MUTED, fontWeight: 500 },
  '& .billing-invoice-action': {
    minWidth: '118px',
    borderRadius: '999px',
    textTransform: 'none',
    fontSize: '11px',
    fontWeight: 600,
    color: ORANGE,
    borderColor: BORDER,
    '&:hover': { borderColor: ORANGE, bgcolor: alpha(ORANGE, 0.06) },
    '&.Mui-disabled': { color: MUTED, borderColor: 'transparent' },
  },

  '& .billing-actions': {
    px: 3,
    pb: 2,
  },
  '& .billing-close': {
    borderRadius: '999px',
    textTransform: 'none',
    fontWeight: 600,
    color: PALETTE_COLORS.forest,
  },
};

export const BillingConfirmDialogStyle: SxProps = {
  '& .MuiDialog-paper': {
    borderRadius: '16px',
  },
  '& .confirm-title': {
    fontSize: '1rem',
    fontWeight: 700,
    color: PALETTE_COLORS.forest,
    pb: 1,
  },
  '& .confirm-row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    padding: '8px 0',
    borderBottom: `1px dashed ${DOTTED}`,
  },
  '& .confirm-row-label': {
    fontSize: '12px',
    color: MUTED,
  },
  '& .confirm-row-value': {
    fontSize: '14px',
    fontWeight: 700,
    color: TEXT,
  },
  '& .confirm-row-value--strong': {
    fontSize: '18px',
    color: ORANGE,
  },
  '& .confirm-note': {
    fontSize: '11px',
    lineHeight: 1.45,
    color: MUTED,
    marginTop: '12px',
  },
  '& .confirm-actions': {
    px: 3,
    pb: 2,
  },
  '& .confirm-cancel': {
    textTransform: 'none',
    fontWeight: 600,
    borderRadius: '999px',
    color: PALETTE_COLORS.forest,
  },
  '& .confirm-submit': {
    textTransform: 'none',
    fontWeight: 700,
    borderRadius: '999px',
    padding: '6px 16px',
    boxShadow: 'none',
    bgcolor: ORANGE,
    color: WHITE,
    '&:hover': { bgcolor: ORANGE_DARK, boxShadow: 'none' },
  },
  '& .confirm-submit--danger': {
    bgcolor: 'error.main',
    '&:hover': { bgcolor: 'error.dark', boxShadow: 'none' },
  },
  '& .confirm-row-value--danger': {
    color: 'error.main',
  },
};
