export const SheetNames = [
  'Golden Source dépa 1 & 2',
  'Access antinuisibles',
  'Api nids',
  'Applic 3D',
  'Allonuizibles',
  'Alphanuisibles',
  'Daniderat',
  'Dennys Innocent',
  "Nuisibl'Est",
  'Rodriguez Père & fils',
  'Radical 33',
  'S3D Hygiene',
  'Simon S3D Hygiene',
  'Seg Antinuisibles',
  '4D EST',
];
