export const SheetNames = [
  'INNO MULTI SERVICE',
  'Golden Source dépa 1 & 2',
  'ACCESS ANTI-NUISIBLES',
  'Rodriguez Père et Fils - Dératisation – Désinsectisation - Désinfection - Dépigeonnage',
  'BAMBOO RESET',
  'LF Proprete',
  'RADICAL',
  "Nuisibl'Est",
  'Applic 3D',
  'ALLONUIZIBLES',
  'Alpha Nuisibles - Dératisation - Désinsectisation - Désinfection',
  'S3D Hygiene',
  'Simon S3D Hygiene',
  'Api nids',
  'Punez',
  'Nuisitime',
  '3D Nuisibles',
  '3D Resultats',
  'Société  Daniderat',
  'segnuisibles',
  '4D EST',
];
