import { SxProps } from '@mui/material';

export const DegradationLevelsStackStyle: SxProps = {
  position: 'relative',
  px: 1.5,
  pt: 1.5,
  pb: 1,
  '& .degradation-legend': {
    position: 'absolute',
    top: -4,
    left: 10,
    transform: 'translateY(-50%)',
    bgcolor: 'white',
    px: 1,
    py: 0.25,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: (theme: any) => theme.palette.secondary.main,
    borderRadius: 1,
    lineHeight: 1,
    zIndex: 3,
  },
  '& .degradation-stack': {
    position: 'relative',
    width: 'fit-content',
  },
  '& .degradation-pill-active': {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 2,
    py: 0.75,
    borderRadius: 50,
    fontWeight: 600,
    boxShadow: '0 3px 12px rgba(0,0,0,.15)',
    cursor: 'pointer',
  },
  '& .degradation-pill-letter': {
    width: 32,
    height: 32,
    borderRadius: '50%',
    bgcolor: 'rgba(255,255,255,.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    fontWeight: 700,
  },
  '& .degradation-pill-value': {
    fontSize: 14,
    fontWeight: 700,
  },
  '& .degradation-popup': {
    position: 'absolute',
    bottom: 'calc(100% + 8px)',
    left: 0,
    minWidth: '100%',
    p: 0.75,
    borderRadius: 2,
    bgcolor: 'white',
    boxShadow: '0 6px 24px rgba(0,0,0,.18)',
    opacity: 0,
    pointerEvents: 'none',
    transition: 'opacity .2s ease',
  },
  '& .degradation-stack:hover .degradation-popup': {
    opacity: 1,
    pointerEvents: 'auto',
  },
  '& .degradation-popup-item': {
    px: 1,
    py: 0.5,
    borderRadius: 50,
    whiteSpace: 'nowrap',
    opacity: 0,
    transform: 'translateY(12px)',
    transition: 'opacity .25s ease, transform .25s ease',
  },
  '& .degradation-stack:hover .degradation-popup-item': {
    opacity: 0.9,
    transform: 'translateY(0)',
  },
  '& .degradation-stack:hover .degradation-popup-item:nth-of-type(1)': { transitionDelay: '.2s' },
  '& .degradation-stack:hover .degradation-popup-item:nth-of-type(2)': { transitionDelay: '.15s' },
  '& .degradation-stack:hover .degradation-popup-item:nth-of-type(3)': { transitionDelay: '.1s' },
  '& .degradation-stack:hover .degradation-popup-item:nth-of-type(4)': { transitionDelay: '.05s' },
  '& .degradation-stack:hover .degradation-popup-item:nth-of-type(5)': { transitionDelay: '0s' },
  '& .degradation-popup-item-active': {
    opacity: 1,
    boxShadow: '0 0 0 2px rgba(0,0,0,.12)',
  },
  '& .degradation-stack:hover .degradation-popup-item-active': {
    opacity: 1,
  },
  '& .degradation-popup-letter': {
    width: 24,
    height: 24,
    borderRadius: '50%',
    bgcolor: 'rgba(255,255,255,.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 700,
    flexShrink: 0,
  },
  '& .degradation-popup-name': {
    fontSize: 12,
    fontWeight: 600,
  },
};
