import { SxProps } from '@mui/material';

export const DegradationLevelsStackStyle: SxProps = {
  position: 'relative',
  px: 1.5,
  pt: 1.5,
  pb: 1,
  '& .degradation-stack': {
    position: 'relative',
    width: 'fit-content',
  },
  '& .degradation-pill-active': {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    px: 2,
    py: 0.75,
    borderRadius: 50,
    fontWeight: 600,
    boxShadow: '0 3px 12px rgba(0,0,0,.15)',
    cursor: 'pointer',
  },
  '& .degradation-pill-icon': {
    width: 34,
    height: 34,
    borderRadius: '50%',
    bgcolor: 'rgba(255,255,255,.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  '& .degradation-pill-icon-svg': {
    fontSize: 20,
  },
  '& .degradation-pill-texts': {
    display: 'flex',
    flexDirection: 'column',
    lineHeight: 1.1,
  },
  '& .degradation-pill-name': {
    fontSize: 13,
    fontWeight: 700,
    whiteSpace: 'nowrap',
    lineHeight: 1.2,
  },
  '& .degradation-pill-desc': {
    fontSize: 11,
    fontWeight: 500,
    whiteSpace: 'nowrap',
    opacity: 0.9,
    lineHeight: 1.2,
  },
  '& .degradation-pill-value': {
    fontSize: 14,
    fontWeight: 700,
    ml: 0.5,
    pl: 1,
    borderLeft: '1px solid rgba(255,255,255,.35)',
  },
  '& .degradation-popup': {
    position: 'absolute',
    bottom: 'calc(100% + 10px)',
    left: 0,
    width: 880,
    maxWidth: '92vw',
    opacity: 0,
    transform: 'translateY(10px)',
    pointerEvents: 'none',
    transition: 'opacity .22s ease, transform .22s ease',
  },
  '& .degradation-stack:hover .degradation-popup': {
    opacity: 1,
    transform: 'translateY(0)',
    pointerEvents: 'auto',
  },
  '& .roof-state-card': {
    bgcolor: '#101a2e',
    p: 1,
    borderRadius: 5,
    boxShadow: '0 18px 50px rgba(0,0,0,.35)',
  },
  '& .roof-state-inner': {
    bgcolor: '#fff',
    borderRadius: 4,
    px: 3,
    py: 2.5,
  },
  '& .roof-state-title': {
    fontSize: 20,
    fontWeight: 800,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: '#1f2a44',
  },
  '& .roof-state-top-divider': {
    my: 1.5,
  },
  '& .roof-state-columns': {
    alignItems: 'stretch',
  },
  '& .roof-state-col': {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    gap: 1,
    px: 1.5,
    py: 1.25,
    border: '1.5px solid transparent',
    borderRadius: 3,
    '&:not(:last-of-type)': {
      borderRight: '1.5px solid #eef0f4',
    },
  },
  '& .roof-state-col-active': {
    borderWidth: '1.5px',
    borderStyle: 'solid',
    '&:not(:last-of-type)': {
      borderRightWidth: '1.5px',
    },
  },
  '& .roof-state-col-icon': {
    width: 56,
    height: 56,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  '& .roof-state-col-icon-svg': {
    fontSize: 28,
  },
  '& .roof-state-col-title': {
    fontSize: 15,
    fontWeight: 700,
    color: '#1f2a44',
  },
  '& .roof-state-col-desc': {
    fontSize: 11.5,
    color: '#9aa3b2',
    lineHeight: 1.3,
  },
  '& .roof-state-bar': {
    gap: 0.75,
    mt: 1.5,
  },
  '& .roof-state-bar-seg': {
    flex: 1,
    height: 10,
    borderRadius: 5,
  },
  '& .roof-state-markers': {
    mt: 0.5,
  },
  '& .roof-state-marker': {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: 18,
  },
  '& .roof-state-dot': {
    width: 7,
    height: 7,
    borderRadius: '50%',
    bgcolor: '#c2c8d2',
  },
  '& .roof-state-pointer': {
    fontSize: 26,
    color: '#1f2a44',
  },
  '& .roof-state-footer': {
    mt: 1,
    p: 1.5,
    borderRadius: 3,
    bgcolor: '#f7f8fa',
    alignItems: 'center',
  },
  '& .roof-state-detected': {
    flex: 1,
  },
  '& .roof-state-footer-icon': {
    width: 52,
    height: 52,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  '& .roof-state-footer-icon-svg': {
    fontSize: 26,
  },
  '& .roof-state-footer-label': {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: '#8a93a3',
  },
  '& .roof-state-detected-value': {
    fontSize: 22,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  '& .roof-state-footer-divider': {
    mx: 3,
  },
  '& .roof-state-score': {
    pr: 2,
  },
  '& .roof-state-score-value': {
    fontSize: 26,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  '& .roof-state-disclaimer': {
    mt: 1.25,
    fontSize: 11,
    color: '#9aa3b2',
  },
};
