import { SxProps } from '@mui/material';

export const ThreeDGenerationModeSwitchStyle: SxProps = {
  position: 'relative',
  display: 'inline-flex',
  marginInline: 1,
  '& .gen-mode-title': {
    position: 'absolute',
    top: 0,
    left: '10px',
    transform: 'translateY(-90%)',
    zIndex: 1,
    paddingInline: '4px',
    background: '#454545',
    borderRadius: '4px',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    fontSize: '10px',
    fontWeight: 500,
    color: '#ffffff',
    lineHeight: 1.2,
  },
  '& .gen-mode-tabs': {
    display: 'inline-flex',
    background: '#454545',
    padding: '3px',
    borderRadius: '999px',
    gap: '2px',
  },
  '& .gen-mode-tab': {
    minHeight: 'unset',
    padding: '6px 16px',
    borderRadius: '999px',
    fontSize: '12px',
    fontWeight: 600,
    color: 'rgba(255,255,255,0.55)',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    textTransform: 'none',
    boxShadow: 'none',
    background: 'transparent',
    border: 'none',
    lineHeight: 1.2,
  },
  '& .gen-mode-tab:hover': {
    color: 'rgba(255,255,255,0.85)',
    boxShadow: 'none',
  },
  '& .gen-mode-tab.active': {
    background: '#ffffff',
    color: '#000000',
    fontWeight: 700,
    boxShadow: '0 1px 4px rgba(0,0,0,0.35)',
  },
  '& .gen-mode-tab.active .MuiSvgIcon-root': {
    color: '#000000',
  },
  '& .gen-mode-tab .MuiSvgIcon-root': {
    fontSize: '16px',
  },
};
