import { PALETTE_COLORS } from '@/bp-theme';
import { SxProps } from '@mui/material';
import { CSSProperties } from 'react';

export const faceMeasureLabelStyle = {
  distanceMeterSpan: (edge: any) => ({
    color: edge.color,
    fontSize: '16px',
    fontWeight: 'bold',
    background: 'rgba(0,0,0,0.75)',
    padding: '4px 10px',
    borderRadius: '6px',
    whiteSpace: 'nowrap',
  }),
  areaSpan: {
    background: 'rgba(0,0,0,0.75)',
    color: '#fff',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '16px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  },
};

export const pointMeasureLineStyle = {
  measuresContainer: {
    background: 'rgba(0,0,0,0.75)',
    color: '#fff',
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  } as CSSProperties,
};

export const roofEdgeMenuItemStyle: SxProps = {
  display: 'flex',
  alignItems: 'center',
  gap: 1,
  fontSize: 12,
  '& .roof-drawer-edge-menu-color': {
    width: 12,
    height: 12,
    borderRadius: '3px',
    border: '1px solid rgba(0,0,0,0.15)',
    flexShrink: 0,
  },
  '& .roof-drawer-edge-menu-label': {
    fontSize: 12,
  },
};

export const roofSurfacesDrawerStyle: SxProps = {
  position: 'absolute',
  inset: 0,
  left: 'auto',
  width: 300,
  '& .roof-drawer-paper': {
    position: 'absolute',
    width: 300,
    boxSizing: 'border-box',
    border: 0,
    borderLeft: '1px solid #ebebeb',
    bgcolor: '#ffffff',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  '& .roof-drawer-header': {
    p: 1.75,
    borderBottom: '1px solid #ebebeb',
    display: 'flex',
    flexDirection: 'column',
    gap: 0.5,
  },
  '& .roof-drawer-header-row': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  '& .roof-drawer-title': {
    fontSize: 13,
    fontWeight: 700,
    color: '#1F1F1F',
  },
  '& .roof-drawer-count': {
    bgcolor: '#FFE4D9',
    color: '#FF521B',
    fontSize: 11,
    fontWeight: 700,
    px: 1,
    py: 0.25,
    borderRadius: '10px',
    minWidth: 22,
    textAlign: 'center',
    lineHeight: 1.4,
  },
  '& .roof-drawer-total': {
    fontSize: 11,
    color: '#6b6b6b',
  },
  '& .roof-drawer-list': {
    p: 1,
    maxHeight: 240,
    overflowY: 'auto',
    borderBottom: '1px solid #ebebeb',
    gap: 0,
  },
  '& .roof-drawer-row': {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    px: 1.25,
    py: 1,
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: '#f7f7f8' },
    '&.selected': { bgcolor: '#FFE4D9' },
  },
  '& .roof-drawer-row-swatch': {
    width: 12,
    height: 12,
    borderRadius: '3px',
    flexShrink: 0,
  },
  '& .roof-drawer-row-info': {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  '& .roof-drawer-row-name': {
    fontSize: 12,
    fontWeight: 600,
    color: '#1F1F1F',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  '& .roof-drawer-row-meta': {
    fontSize: 11,
    color: '#6b6b6b',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .roof-drawer-row-input': {
    flex: 1,
    '& .MuiInput-input': { fontSize: 12, fontWeight: 600, py: 0 },
  },
  '& .roof-drawer-row-edit': {
    width: 26,
    height: 26,
    color: '#6b6b6b',
    opacity: 0,
    transition: 'opacity 0.15s',
    '& svg': { fontSize: 14 },
    '&:hover': { bgcolor: 'rgba(0,0,0,0.06)', color: '#1F1F1F' },
  },
  '& .roof-drawer-row:hover .roof-drawer-row-edit': { opacity: 1 },
  '& .roof-drawer-row.selected .roof-drawer-row-edit': { opacity: 1 },
  '& .roof-drawer-detail': {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    p: 1.75,
    gap: 1.5,
  },
  '& .roof-drawer-detail-header': {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
  },
  '& .roof-drawer-detail-color': {
    width: 14,
    height: 14,
    borderRadius: '4px',
    flexShrink: 0,
  },
  '& .roof-drawer-detail-title': {
    flex: 1,
    fontSize: 14,
    fontWeight: 700,
    color: '#1F1F1F',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  '& .roof-drawer-detail-stats': {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 0.75,
  },
  '& .roof-drawer-detail-stat': {
    bgcolor: '#fafafb',
    border: '1px solid #ebebeb',
    borderRadius: '6px',
    p: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 0.25,
  },
  '& .roof-drawer-detail-stat-label': {
    fontSize: 10,
    fontWeight: 600,
    color: '#6b6b6b',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
  },
  '& .roof-drawer-detail-stat-value': {
    fontSize: 13,
    fontWeight: 700,
    color: '#1F1F1F',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .roof-drawer-detail-section': {
    fontSize: 11,
    fontWeight: 700,
    color: '#6b6b6b',
    textTransform: 'uppercase',
    letterSpacing: '0.3px',
    mt: 0.5,
  },
  '& .roof-drawer-detail-empty': {
    fontSize: 12,
    color: '#6b6b6b',
    fontStyle: 'italic',
  },
  '& .roof-drawer-detail-edges': {
    gap: 0.75,
    display: 'flex',
    flexDirection: 'column',
  },
  '& .roof-drawer-edge-row': {
    display: 'grid',
    gridTemplateColumns: '1fr auto auto',
    alignItems: 'center',
    gap: 1,
    bgcolor: '#fafafb',
    border: '1px solid #ebebeb',
    borderRadius: '6px',
    px: 1,
    py: 0.75,
  },
  '& .roof-drawer-edge-type-select': {
    minWidth: 0,
    '& .MuiSelect-select': {
      py: 0.25,
      pr: '20px !important',
      display: 'flex',
      alignItems: 'center',
      minWidth: 0,
      fontSize: 12,
    },
    '& .MuiSelect-icon': { color: '#6b6b6b' },
    '&:before, &:after': { display: 'none' },
  },
  '& .roof-drawer-edge-type-value': {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    minWidth: 0,
  },
  '& .roof-drawer-edge-type-label': {
    fontSize: 12,
    fontWeight: 500,
    color: '#1F1F1F',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    minWidth: 0,
  },
  '& .roof-drawer-edge-color': {
    width: 10,
    height: 10,
    borderRadius: '2px',
    border: '1px solid rgba(0,0,0,0.15)',
    flexShrink: 0,
  },
  '& .roof-drawer-edge-length': {
    fontSize: 11,
    color: '#6b6b6b',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .roof-drawer-edge-slope': {
    fontSize: 11,
    fontWeight: 600,
    color: '#1F1F1F',
    fontVariantNumeric: 'tabular-nums',
    minWidth: 32,
    textAlign: 'right',
  },
  '& .roof-drawer-measures-section': {
    borderTop: '1px solid #ebebeb',
    display: 'flex',
    flexDirection: 'column',
  },
  '& .roof-drawer-measures-header': {
    p: 1.75,
    pb: 0.5,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  '& .roof-drawer-measures-title': {
    fontSize: 13,
    fontWeight: 700,
    color: '#1F1F1F',
  },
  '& .roof-drawer-measures-count': {
    bgcolor: '#D9EAFF',
    color: '#1B6EF3',
    fontSize: 11,
    fontWeight: 700,
    px: 1,
    py: 0.25,
    borderRadius: '10px',
    minWidth: 22,
    textAlign: 'center',
    lineHeight: 1.4,
  },
  '& .roof-drawer-measures-list': {
    p: 1,
    maxHeight: 200,
    overflowY: 'auto',
    gap: 0,
  },
  '& .roof-drawer-measure-row': {
    display: 'flex',
    alignItems: 'center',
    gap: 1.25,
    px: 1.25,
    py: 0.75,
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background 0.12s',
    '&:hover': { bgcolor: '#f7f7f8' },
    '&.selected': { bgcolor: '#D9EAFF' },
  },
  '& .roof-drawer-measure-icon': {
    width: 22,
    height: 22,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '4px',
    flexShrink: 0,
    fontSize: 13,
  },
  '& .roof-drawer-measure-info': {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
  },
  '& .roof-drawer-measure-name': {
    fontSize: 12,
    fontWeight: 600,
    color: '#1F1F1F',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  '& .roof-drawer-measure-meta': {
    fontSize: 11,
    color: '#6b6b6b',
    fontVariantNumeric: 'tabular-nums',
  },
  '& .roof-drawer-measure-input': {
    flex: 1,
    '& .MuiInput-input': { fontSize: 12, fontWeight: 600, py: 0 },
  },
  '& .roof-drawer-measure-actions': {
    display: 'flex',
    alignItems: 'center',
    gap: 0,
    opacity: 0,
    transition: 'opacity 0.15s',
  },
  '& .roof-drawer-measure-row:hover .roof-drawer-measure-actions': { opacity: 1 },
  '& .roof-drawer-measure-row.selected .roof-drawer-measure-actions': { opacity: 1 },
  '& .roof-drawer-measure-action-btn': {
    width: 24,
    height: 24,
    color: '#6b6b6b',
    '& svg': { fontSize: 14 },
    '&:hover': { bgcolor: 'rgba(0,0,0,0.06)', color: '#1F1F1F' },
  },
  '& .roof-drawer-measure-delete-btn': {
    width: 24,
    height: 24,
    color: '#6b6b6b',
    '& svg': { fontSize: 14 },
    '&:hover': { bgcolor: 'rgba(220,38,38,0.08)', color: '#dc2626' },
  },
};

export const annotator3DFloatingActionsStyle: SxProps = {
  position: 'absolute',
  bottom: 16,
  left: '50%',
  transform: 'translateX(-50%)',
  zIndex: 999,
  background: 'rgba(31,31,31,0.85)',
  backdropFilter: 'blur(8px)',
  borderRadius: '12px',
  px: 0.5,
  py: 0.5,
  boxShadow: '0 2px 12px rgba(0,0,0,0.25)',
  '& .measure-btn': {
    color: PALETTE_COLORS.white,
    fontSize: 11,
    textTransform: 'none',
    borderRadius: '8px',
    px: 1.5,
    py: 0.5,
    minWidth: 0,
    whiteSpace: 'nowrap',
    transition: 'all 0.15s ease',
    '&:hover': {
      background: 'rgba(255,255,255,0.1)',
    },
  },
  '& .measure-btn-active': {
    background: PALETTE_COLORS.neon_orange,
    '&:hover': {
      background: '#e8431a',
    },
  },
  '& .MuiDivider-root': {
    borderColor: 'rgba(255,255,255,0.15)',
    my: 0.5,
  },
};

export const polygonMeasureLineStyle = {
  measureSpan: (color: any) => ({
    color,
    fontSize: '14px',
    fontWeight: 'bold',
    background: 'rgba(0,0,0,0.75)',
    padding: '3px 8px',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
  }),
  measuresContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  } as CSSProperties,
  areaDiv: {
    background: 'rgba(0,0,0,0.75)',
    color: '#fff',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: 'bold',
    whiteSpace: 'nowrap',
  } as CSSProperties,
};
