name: Monitor 3D, Detection on instatus

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      service:
        description: 'Monitor (3d, detection, or both)'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - 3d
          - detection

env:
  AWS_REGION: eu-west-3
  PROD_USERPOOL_ID: eu-west-3_FRKp6Y3Gx
  PROD_WEBCLIENT_ID: 1rof83p44k83l5lc8gfk6sbtam
  PROD_OAUTH_DOMAIN: bpartners.auth.eu-west-3.amazoncognito.com
  PROD_REDIRECT_SUCCESS: https://dashboard.bpartners.app/login/success

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: 3d
            spec: 'src/**/3D_generator.it.cy.ts'
            s3_folder: cypress-3D-videos
            is_monitoring_3d: 'true'
          - service: detection
            spec: 'src/**/detection.it.cy.ts'
            s3_folder: cypress-detection-videos
            is_monitoring_3d: 'false'

    if: |
      github.event_name == 'schedule' ||
      inputs.service == 'both' ||
      inputs.service == matrix.service

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
          verbose: false
          arch: amd64
          rootdir: ''
          workdir: ''

      - name: Connect to Bpartners Imagery AWS CodeArtifact
        run: |
          sh ./initAWS.sh imagery ${{ secrets.BPARTNERS_IMAGERY_AWS_ACCESS_KEY_ID }} ${{ secrets.BPARTNERS_IMAGERY_AWS_SECRET_ACCESS_KEY }} eu-west-3
          sh ./initNpmrc.sh imagery annotator-imagery-store npm-bpartners-imagery-app 205205101409

      - name: Connect to HEI AWS CodeArtifact
        run: |
          sh ./initAWS.sh hei ${{ secrets.HEI_AWS_ACCESS_KEY_ID }} ${{ secrets.HEI_AWS_SECRET_ACCESS_KEY }} ${{ secrets.HEI_AWS_REGION }}
          sh ./initNpmrc.sh hei hei-store npm-hei-school 088312068315

      - name: Connect to BPartners AWS CodeArtifact
        run: |
          sh ./initAWS.sh bpartners ${{ secrets.BPARTNERS_AWS_ACCESS_KEY_ID }} ${{ secrets.BPARTNERS_AWS_SECRET_ACCESS_KEY }} ${{ secrets.BPARTNERS_AWS_REGION }}
          sh ./initNpmrc.sh bpartners bpartners-store npm-bpartners-app 688605879718

      - run: npm install --legacy-peer-deps

      - name: Setup Env variables
        run: |
          echo REACT_APP_AWS_REGION=${{ env.AWS_REGION }} > .env
          echo REACT_APP_USERPOOL_ID=${{ env.PROD_USERPOOL_ID }} >> .env
          echo REACT_APP_WEBCLIENT_ID=${{ env.PROD_WEBCLIENT_ID }} >> .env
          echo REACT_APP_OAUTH_DOMAIN=${{ env.PROD_OAUTH_DOMAIN }} >> .env
          echo REACT_APP_REDIRECT_SUCCESS=${{ env.PROD_REDIRECT_SUCCESS }} >> .env
          echo REACT_APP_BPARTNERS_API_URL=https://api.dashboard.birdia.fr >> .env
          echo REACT_APP_IT_USERNAME=${{ secrets.IT_USERNAME }} >> .env
          echo REACT_APP_IT_PASSWORD='${{ secrets.IT_PASSWORD }}' >> .env
          echo REACT_APP_PROD_URL='${{ secrets.REACT_APP_PROD_URL }}' >> .env
          echo REACT_APP_IT_ONBOARD_USERNAME=${{ secrets.REACT_APP_IT_ONBOARD_USERNAME }} >> .env
          echo REACT_APP_IT_ONBOARD_PASSWORD_1=${{ secrets.REACT_APP_IT_ONBOARD_PASSWORD_1 }} >> .env
          echo REACT_APP_IT_ONBOARD_PHONE_NUMBER=${{ secrets.REACT_APP_IT_ONBOARD_PHONE_NUMBER }} >> .env
          echo INSTATUS_API_KEY=${{ secrets.INSTATUS_API_KEY }} >> .env
          echo INSTATUS_PAGE_ID=${{ secrets.INSTATUS_PAGE_ID }} >> .env
          echo INSTATUS_3D_COMPONENT_ID=${{ secrets.INSTATUS_3D_COMPONENT_ID }} >> .env
          echo DASHBOARD_ADMIN_API_KEY=${{ secrets.DASHBOARD_ADMIN_API_KEY }} >> .env
          echo EXCLUDE_INSTATUS_IT_SPEC=false >> .env
          echo INSTATUS_DETECTION_COMPONENT_ID=${{ secrets.INSTATUS_DETECTION_COMPONENT_ID }} >> .env

      - name: Monitor ${{ matrix.service }}
        id: monitor
        run: npx cypress run --browser chrome --headless --spec '${{ matrix.spec }}'
        continue-on-error: true,

      - name: Upload video to S3
        if: ${{ always() && steps.monitor.outcome == 'failure' }}
        run: |
          aws s3 cp cypress/videos/ s3://${{ secrets.CYPRESS_S3_BUCKET }}/${{ matrix.s3_folder }}/$(date +%Y-%m-%d_%H-%M-%S)/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BPARTNERS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BPARTNERS_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.BPARTNERS_AWS_REGION }}
